name: Snyk Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  snyk-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Open Source (SCA  in Audit Mode)
        run: snyk test --all-projects --org=1047f1f4-2b85-412a-9844-faac83a1207b

      - name: Run Snyk Code (SAST in Audit Mode)
        run: snyk code test
